<?php

namespace app\modules\shop\controllers;

use app\models\Categories;
use app\models\Users;
use yii\base\Exception;
use yii\web\Controller;
use Yii;

/**
 */
class CatsController extends Controller
{

    public function init()
    {
        parent::init();
        if (!Yii::$app->user->isGuest && Yii::$app->user->identity->role == Users::ROLE_ADMIN) {
            return true;
        }
    }

    public function beforeAction($action)
    {
        Yii::$app->request->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new Categories();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView() {
        $model = $this->loadModel();
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionEdit() {
        $model = $this->loadModel();
        foreach (array_keys(Yii::$app->request->post('Categories')) as $key) {
            $model->{$key} = Yii::$app->request->post('Categories')[$key];
        }
        if ($model->save()) {
            return $this->redirect('/shop/cats/view?id=' . Yii::$app->request->get()['id']);
        }
        return $this->redirect('/');
    }

    private function loadModel() {
        if ($id = Yii::$app->request->get()['id']) {
            if ($model = Categories::findOne($id)) {
                return $model;
            }
        }
        throw new Exception('Товар не найден!');
    }
}
