<?php

namespace app\modules\shop\controllers;

use app\models\Users;
use yii\base\Exception;
use yii\web\Controller;
use Yii;

/**
 * Product controller for the `shop` module
 */
class UsersController extends Controller
{

    public function init()
    {
        parent::init();
        if (!Yii::$app->user->isGuest && Yii::$app->user->identity->role == Users::ROLE_ADMIN) {
            return true;
        }
        $this->redirect('/auth');
    }

    public function beforeAction($action)
    {
        Yii::$app->request->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new Users();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView() {
        $model = $this->loadModel();
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionDelete() {
        $model = $this->loadModel();
        $model->delete();
        $this->redirect('/shop/users/index');
    }

    public function actionBlock() {
        $model = $this->loadModel();
        $model->status = Users::STATUS_BAN;
        $model->new_pass = 'pass';
        $model->repeat_pass = 'pass';
        $model->save();
        $this->redirect('/shop/users/index');
    }

    public function actionUnblock() {
        $model = $this->loadModel();
        $model->status = Users::STATUS_ACTIVE;
        $model->new_pass = 'pass';
        $model->repeat_pass = 'pass';
        $model->save();
        $this->redirect('/shop/users/index');
    }

    private function loadModel() {
        if ($id = Yii::$app->request->get()['id']) {
            if ($model = Users::findOne($id)) {
                return $model;
            }
        }
        throw new Exception('Товар не найден!');
    }
}
